### ISSUE TITLE
Text Results not saved 

### ISSUE THREAD

**Issue by deXxterlab97** [CSMarkBenchmark/CSMarkCore#5] opened 2018-10-16 22:30 UTC
Results does not get saved at all (at least not where they suppose to be). Running Core (CLI) 33.2

OS: Xubuntu 18.04.1 LTS

System specs: i3 5005u, 8gb ram, HD 5500 igpu

**Comment by AluminiumTech** [comment] 2018-10-18 15:55
I can confirm there appears to be an issue with saving results text files.

I will look into this further.

![nofile](https://user-images.githubusercontent.com/14107316/47167480-87fb9600-d2f6-11e8-8093-06b6daa0eaf0.png)

![notextfile](https://user-images.githubusercontent.com/14107316/47167483-8d58e080-d2f6-11e8-9636-8d00c1bfef83.png)

**Comment by AluminiumTech** [comment] 2018-10-18 15:56
I'll try to replicate this on Windows to see if it is a broad issue or only affecting Linux users.

**Comment by AluminiumTech** [comment] 2018-10-24 20:33
@deXxterlab97  This definitely seems to be a linux only thing.

Cos the file is saved on Windows.

![image](https://user-images.githubusercontent.com/14107316/47459595-77ef2500-d7d4-11e8-98bc-f1c8bc996f7f.png)

I will try to look into the issue further.

**Comment by AluminiumTech** [comment] 2018-11-02 14:20
This is fixed in CSMarkLib 1.4.7 and CSMarkCore will use CSMarkLib 1.4.7

**Closed by AluminiumTech** 2018-11-02 14:20 UTC
Labels: bug, linux
